name: mi_utem
description: Plataforma académica para estudiantes de la Universidad Tecnológica Metropolitana (UTEM)

version: 2.4.0+38

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grpc: ^1.0.0
  protobuf: ^0.13.12
  flushbar: ^1.8.2
  video_player: ^2.1.0
  tinycolor: ^1.0.2
  diagonal_scrollview: ^0.2.0
  url_launcher: ^5.0.3
  shared_preferences: ^0.4.3
  font_awesome_flutter: ^8.5.0
  flutter_masked_text: ^0.8.0
  flutter_statusbar: ^0.0.1
  dotted_border: ^1.0.2
  barcode_flutter: ^1.0.2
  flutter_keyboard_visibility: ^4.0.0
  recase: ^2.0.1
  flare_flutter: ^1.5.4
  carousel_slider: ^3.0.0
  dio: ^4.0.0-beta7
  flutter_spinkit: ^4.1.2+1
  dio_http_cache:
    git:
      url: git://github.com/shinayser/dio-http-cache.git
  flutter_secure_storage: ^3.3.5
  charts_flutter: ^0.10.0
  mdi: ^3.0.0
  sentry_flutter: ^4.1.0-nullsafety.0
  firebase_core: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_remote_config: ^0.9.0-dev.1
  firebase_in_app_messaging: ^0.4.0
  firebase_messaging: ^9.1.2
  cloud_firestore: ^1.0.5
  html: ^0.14.0+4
  gradient_widgets: ^0.5.1
  timer_button: ^1.0.1
  cached_network_image: ^2.5.0
  circular_profile_avatar: ^1.0.6
  photo_view: ^0.10.3
  custom_refresh_indicator: ^0.9.0
  in_app_review: ^1.0.4
  simple_gesture_detector: ^0.1.6
  extended_image: ^3.0.0
  image_editor: ^0.7.3
  image_editor_pro: ^1.0.9
  image_picker: ^0.6.7+22
  package_info: ^0.4.3+4
  in_app_update: ^1.1.15
  integration_test: ^1.0.2+2
  badges: ^1.1.6
  flutter_windowmanager: ^0.0.2
  clipboard: ^0.1.2+8
  flutter_markdown: ^0.6.1

  awesome_notifications: 
    git:
      url: git://github.com/rafaelsetragni/awesome_notifications.git
  get: ^4.1.4
  

dependency_overrides:
  crypto: ^3.0.0
  path_provider: ^2.0.1
  http: ^0.13.0
  package_info: ^2.0.0
  plugin_platform_interface: ^2.0.0
  http_parser: ^4.0.0
  dio: ^4.0.0-beta7
  integration_test: ^1.0.2+2
  args: ^2.0.0
  awesome_notifications: ^0.0.5+8
  permission_handler: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:

    - assets/videos/login_bg.mp4
    - assets/images/login_bg.png
    - assets/images/utem_logo_color_blanco.png
    - assets/images/utem_logo_color_azul.png
    - assets/images/utem_logo_negativo.png
    - assets/images/utem_isotipo_negativo.png
    - assets/animations/monito.flr
    - assets/animations/utem.flr
    - assets/images/sibutem.jpg
