name: mi_utem
description: Plataforma académica para estudiantes de la Universidad Tecnológica
  Metropolitana (UTEM)
publish_to: none

version: 2.4.0+38

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_notifications:
    git:
      url: https://github.com/aaqibism/awesome_notifications.git
  badges: ^2.0.2
  barcode_flutter:
    git:
      url: https://github.com/venosyd/barcode.flutter.git
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  circular_profile_avatar: ^2.0.5
  clipboard: ^0.1.3
  cloud_firestore: ^3.1.10
  custom_refresh_indicator: ^1.0.0
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.6
  dio_cache_interceptor_hive_store: ^3.1.1
  dotted_border: ^2.0.0+2
  extended_image: ^6.0.2+1
  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1
  firebase_in_app_messaging: ^0.6.0+9
  firebase_messaging: ^11.2.11
  firebase_remote_config: ^2.0.2
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_keyboard_visibility: ^5.0.3
  flutter_markdown: ^0.6.1
  flutter_masked_text:
    git:
      url: https://github.com/vitorhm/flutter-masked-text.git
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  flutter_windowmanager: ^0.2.0
  font_awesome_flutter: ^10.0.0
  get: ^4.1.4
  gradient_widgets: ^0.6.0
  html: ^0.15.0
  image_editor: ^1.0.0
  image_picker: ^0.8.4+2
  in_app_review: ^2.0.3
  mdi: ^5.0.0-nullsafety.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  permission_handler: ^9.2.0
  photo_view: ^0.13.0
  qr_flutter: ^4.0.0
  recase: ^4.0.0
  responsive_framework: ^0.1.0
  screenshot: ^1.2.3
  sentry: ^6.0.0
  share_plus: ^4.0.1
  shared_preferences: ^2.0.7
  simple_gesture_detector: ^0.2.0
  url_launcher: ^6.0.10
  video_player: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/videos/login_bg.mp4
    - assets/images/login_bg.png
    - assets/images/utem_logo_color_blanco.png
    - assets/images/utem_logo_color_azul.png
    - assets/images/utem_logo_negativo.png
    - assets/images/utem_isotipo_negativo.png
    - assets/animations/monito.flr
    - assets/animations/utem.flr
    - assets/images/sibutem.jpg
    - .env
